### ISSUE TITLE
Maul

### ISSUE THREAD

**Issue by Kanoshiko** [Adirelle/AdiButtonAuras#103]
For druid tank, it can be cool to make a "Maul" enlightenment went rage ressource is greater than or equal 80.

**Comment by arcadepro** [comment]
You could copy this and change the spell IDs to work for you. I wasn't a big fan of these type of rules originally but I think having them available is better than not having them at all. You can always disable them/not use them.
```
return Configure {
			"Shield Barrier",
			L['Suggest using Shield Barrier at 60 Rage or more. Flash at maximum Rage.'],
			112048, -- Shield Barrier
			"player",
			{ "UNIT_POWER_FREQUENT", "UNIT_MAXPOWER" },
			function(_, model)
				local power = UnitPower("player")
				if power == UnitPowerMax("player") then
					model.highlight = "flash"
				elseif power >= 60 then
					model.hint = true
				end
			end,
		}
```
