### ISSUE TITLE
Dispel Magic for Priest: typo in lua?

### ISSUE THREAD

**Issue by ayalon** [Adirelle/AdiButtonAuras#136]
Hi Adirelle

I tested the the current version 1.8.8 and found that "Dispel Magic" is not working. I think there is a tyoe because the brace was closed to early
correct code:

```
		DISPEL = {
			[527] = "HELPFUL", -- Purify
			[528] = "HARMFUL", -- Dispel Magic
		},

priest.lua in LibPlayerspell

**Comment by Adirelle** [comment]
Does 1.8.10 fix it ?

**Comment by Rainrider** [comment]
This is fixed
