### ISSUE TITLE
User rule not showing up (Templar's Verdict and Holy Power)

### ISSUE THREAD

**Issue by Specksy** [Adirelle/AdiButtonAuras#137]
ShowPower {
    85256, -- Templar's Verdict
    "HOLY_POWER",
    3,
    "flash"
}

That's my user rule. It doesn't show up when I hover over Templar's Verdict in the set spells thing. Any ideas?

**Comment by arcadepro** [comment]
```
return ShowPower {
	100, -- Charge
	"RAGE",
	5,
	"flash",
	}
```
This rule above works. It's useless but it works. Check for typos and duplicate rules. And reload interface of course.

```
return ShowPower {
	85256, -- Templar's Verdict
	"HOLY_POWER",
	3,
	"flash",
	}
```

**Comment by Adirelle** [comment]
Examples added to https://github.com/Adirelle/AdiButtonAuras/wiki/Example-rules.

**Comment by Adirelle** [comment]
I confirm there is a rule to display Holy Power on Templar's Verdict. It may fails from some reason through (bad id ?). And should flash at 5 Holy Power.

However, I think there is something funny with Paladin Holy Power's, like have maximum 3 Holy Power but also a stock of 2.

**Comment by Rainrider** [comment]
Closing because of lack of feedback.
