### ISSUE TITLE
Empowered Seals

### ISSUE THREAD

**Issue by Snowdome** [Adirelle/AdiButtonAuras#140]
Wanted to show the remaining duration of empowered seal buffs on the correspond seal spells, but no idea what to do in the user rules.
Here are the spell ids:
Seal of Justice with Turalyon's Justice (156987)
Seal of Insight with Uther's Insight (156988)
Seal of Righteousness with Liadrin's Righteousness (156989)
Seal of Truth (31801) with Maraad's Truth (156990)

**Comment by Adirelle** [comment]
I'd like to add Seals and Judgement to AdiButtonAuras, but I need to understand the mechanisms (seems I don't play a paladin myself). Please correct me if I'm wrong:

* The paladin can have one active, permanent Seal at a time,
* Each Seal has a specific effect. Some of them apply a debuff to the target through melee attacks.
* Judgment is an instant spell with 6-second cooldown. It requires an active Seal.
* Empowered Seals adds an 20-second self-buff when Judgment is used, depending on the the active Seal.

That's many information to display on only a few spells, so I am not sure what should be displayed.

* Should we display the base debuffs of Seals on Attack ?
* Should we display the current active Seal on Seals ?
* Should we display the duration of Empowered Seal effects over that ?

Any thoughts ?

**Comment by Snowdome** [comment]
Thanks for the response and apologies for late reply (I totally forget about it after some days...)

The first four points are correct. FYI, paladins now have their seals in the old aura bar. As of this moment, none of the debuff are reflected on the seals.

It's true that there are many information, and here are some more facts and opinions:
* Seal of Truth is the default single-target DPS seal that applies a DoT debuff (Censure) on the target, stacking up to 5 times, lasting for 20 seconds without further melee attacks.
* Seal of Justice inflicts a slow debuff on the target. The mechanism is the same as Seal of Truth except the debuff lasts only for 8 seconds.
* Depends on situation, these debuffs can actually be maintained on several targets, but since it's hard to keep track of that in a mere icon, I would say ignore them completely.
* Seal of Righteousness and Seal of Insight inflict no debuff.

So, I would say ignore the default debuffs and focus only on Empowered Seals, as they are the ones that are harder to maintain yet crucial to DPS performance. To maximize Empowered Seals, I will need to cast Judgment with Seal of Truth and Seal of Righteousness every 20 seconds respectively and this is where I want the addon to aid me.

**Comment by Rainrider** [comment]
This should do what you need:
```lua
return {
	BuffAliases {
		 20164, -- Seal of Justice
		156987, -- Turalyon's Justice
	},
	BuffAliases {
		 20165, -- Seal of Insight
		156988, -- Uther's Insight
	},
	BuffAliases {
		 20154, -- Seal of Righteousness
		156989, -- Liadrin's Righteousness
	},
	BuffAliases {
		 31801, -- Seal of Truth
		156990, -- Maraad's Truth
	},
}
```
Please add this as a user rule and restrict it to the paladin class.

Could you also please confirm the individual seal spell ids as I simply got them from the spellbook and those are not always the same on the action bar, especially if they are modified by a glyph or a talent. To do this please toggle the "Debugging Tooltip" option in ABA on and drag every seal spell onto an action bar ("Debugging Tooltip" does not currently work on the stance/aura bar). Please look up the ids after modifying the seals (e.g with Glyph of Immediate Truth) and share the results here so that I can add those to LibPlayerSpells. Thank you in advance.

**Comment by Snowdome** [comment]
I can confirm the above spell IDs are correct, but the script is doing nothing to the icons. Adding Glyph of Immediate Truth did not change the spell ID either.

**Comment by Rainrider** [comment]
Yes, this is my fault, the rule to use is `SelfBuffAliases` and not `BufAliases`. BuffAliases should take the player into account when no other friendly target is selected though.

I have added those to LibPlayerSpells now. Maraad's Truth and Censure are currently both displayed on Seal of Truth, but you could turn off the one you don't like.

Thank you very much for confirming the spell ids!
