### ISSUE TITLE
Spellsteal / Tranquilizing Shot

### ISSUE THREAD

**Issue by BOLLE007xp** [Adirelle/AdiButtonAuras#144]
dispels (spellsteal ID:30449 and tranquilizing Shot ID:19801) don't seem to work anymore, although at least tranq shot did work a few weeks ago if i remember correctly.
even if i turn them to "inverted" the highlighted border shows up, but it doesn't disapper when it should.

**Comment by Adirelle** [comment]
Which version is failing and in which case ? I don't have any issue with Tranquilizing Shot.

**Comment by flcl33** [comment]
I can confirm that auras are not works for spellsteal on my mage, though I have not had any trouble with tranquilizing shot. This is for version 1.9 and I have checked that it is enabled under the option menu.

**Comment by Rainrider** [comment]
Spellsteal is currently not included in LibDispellable, which causes it to now show in AdiButtonAuras.

@Adirelle I have some other pending work on LD as well and would also include Spellsteal. Should be ready to PR later today or tomorrow evening, if that is ok with you.

**Comment by Rainrider** [comment]
This is fixed in Adirelle/LibDispellable-1.0@e2a34a83e736d40aec7d7cb796fb4b61316bb05b
ABA update on wowace is pending
