### ISSUE TITLE
All buttons have gone black

### ISSUE THREAD

**Issue by ahsanali78** [Adirelle/AdiButtonAuras#145]
I updated the addon yesterday.

After the update, all my action bar buttons are black.

I am using RealUI which I believe uses Masque and Bartender.

**Comment by sinayion** [comment]
I can confirm the same issue. If AdiButtonAuras is enabled with either Bartender or Masque, all buttons are black (the default empty button colouring), but they still work; you just can't see the icons.

**Comment by Adirelle** [comment]
Which versions of Bartender, Masque ? Which skins are you using ? I can't reproduce it with latest versions of Masque and Bartender4, nor defaults skins.

**Comment by ahsanali78** [comment]
If I disable Masque, the icons show.

Bartender4 4.6.5
Masque 6.0.0

On Sat, Jan 10, 2015 at 4:24 AM, Guillaume Perréal <notifications@github.com

**Comment by Adirelle** [comment]
Which skin are you using ? Is Masque configured to use the same skin for AdiButtonAuras and Bartender ?

**Comment by sinayion** [comment]
Sorry, I posted just before going to bed, had zero time. I'll do a full QA check once I get home; I work in video game QA.

**Comment by sinayion** [comment]
Addons:
AdiButtonAuras - Release - 1.8.10
Bartender4 - Release - 4.6.5
Masque - Release - 6.0.0
Masque Skinner: Blizz Buffs - Release - 5.0.6
Masque: CleanUI - Release - 6.4

Steps to reproduce - addon combinations:
1) All enabled
Issue occurs, all buttons appear blank.

2) AdiButtonAuras & Bartender4 & Masque enabled (without Masque skins)
Issue occurs, all buttons appear blank.

3) AdiButtonAuras & Masque enabled (without Masque skins)
Issue does not occur.

4) AdiButtonAuras & Masque enabled (with Masque skins)
Issue does not occur.

5) AdiButtonAuras & Bartender4 enabled
Issue does not occur

Let me know if you want another test. No other addons were enabled during any of the above tests.

**Comment by Adirelle** [comment]
Ok, so there seems to be a new option in masque "background texture". When enabled, the texture is also shown on AdiButtonAuras overlays. This causes them to mask the underlying button.

**Comment by sinayion** [comment]
Thanks for finding this, and addressing it :)
