### ISSUE TITLE
Note: AddOn AdiButtonAuras attempted to call a protected function (DominosActionButton20:Show()) during combat lockdown.

### ISSUE THREAD

**Issue by brackenwow** [Adirelle/AdiButtonAuras#146]
This happens to me when spending 5 combo points on Ferocious Bite as a Feral Druid

Date: 2015-01-10 19:45:54
ID: 1
Error occured in: AddOn: AdiButtonAuras
Count: 1
Message: Note: AddOn AdiButtonAuras attempted to call a protected function (DominosActionButton20:Show()) during combat lockdown.
Debug:
   [C]: Show()
   ..\FrameXML\ActionButton.lua:301:
      ..\FrameXML\ActionButton.lua:275
   [C]: ActionButton_Update()
   ..\FrameXML\ActionButton.lua:577: ActionButton_OnEvent()
   ..\FrameXML\ActionButton.lua:137:
      ..\FrameXML\ActionButton.lua:134
Locals:
None
AddOns:
  Swatter, v5.21c.5521 (SanctimoniousSwamprat)
  NPCScanOverlay, v6.0.3.4
  NPCScanOverlayBroker, v1.2.5
  AdiButtonAuras, v1.8.10
  Altoholic, vr152
  AucAdvanced, v5.21c.5521 (SanctimoniousSwamprat)
  AucFilterBasic, v5.21c.5521 (SanctimoniousSwamprat)
  AucFilterOutlier, v5.21c.5521.5459(5.21c/embedded)
  AucMatchUndercut, v5.21c.5521.5507(5.21c/embedded)
  AucStatHistogram, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatiLevel, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatPurchased, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatSales, v5.21c.5521.5476(5.21c/embedded)
  AucStatSimple, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatStdDev, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatWOWEcon, v5.21c.5521.5323(5.21c/embedded)
  AucUtilAHWindowControl, v5.21c.5521.5347(5.21c/embedded)
  AucUtilAppraiser, v5.21c.5521.5495(5.21c/embedded)
  AucUtilAskPrice, v5.21c.5521.5447(5.21c/embedded)
  AucUtilAutoMagic, v5.21c.5521.5443(5.21c/embedded)
  AucUtilCompactUI, v5.21c.5521.5496(5.21c/embedded)
  AucUtilEasyBuyout, v5.21c.5521.5507(5.21c/embedded)
  AucUtilFixAH, v5.21c.5521 (SanctimoniousSwamprat)
  AucUtilItemSuggest, v5.21c.5521.5417(5.21c/embedded)
  AucUtilPriceLevel, v5.21c.5521.5458(5.21c/embedded)
  AucUtilScanButton, v5.21c.5521.5403(5.21c/embedded)
  AucUtilScanFinish, v5.21c.5521.5515(5.21c/embedded)
  AucUtilScanProgress, v5.21c.5521.4979(5.21c/embedded)
  AucUtilScanStart, v5.21c.5521.5347(5.21c/embedded)
  AucUtilSearchUI, v5.21c.5521.5515(5.21c/embedded)
  AucUtilSimpleAuction, v5.21c.5521.5514(5.21c/embedded)
  AucUtilVendMarkup, v5.21c.5521.4828(5.21c/embedded)
  Auctionator, v3.2.2
  AutoRepair, v
  Babylonian, v5.1.DEV.332(/embedded)
  BadBoy, v12.504
  BagBrother, v6.0.16
  Bagnon, v6.0.16
  BankStack, vv35
  BulkOrder, vv1.05
  CCTracker, v2.0.3
  Configator, v5.1.DEV.376(/embedded)
  ConfirmLootRoll, v
  CrapAway, v
  DataStore, vr52
  DataStoreAchievements, vr38
  DataStoreAgenda, vr20
  DataStoreAuctions, v6.0.001
  DataStoreCharacters, vr30
  DataStoreContainers, v6.0.002
  DataStoreCrafts, vr64
  DataStoreCurrencies, v6.0.002
  DataStoreGarrisons, vr8
  DataStoreInventory, vr41
  DataStoreMails, vr40
  DataStorePets, vr36
  DataStoreQuests, vr32
  DataStoreReputations, v6.0.002
  DataStoreSpells, v6.0.002
  DataStoreStats, v6.0.002
  DataStoreTalents, v6.0.002
  DBMCore, v
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  Dominos, v6.0.13
  DominosCast, v
  DominosEncounter, v
  DominosRoll, v
  DominosXP, v
  GarrisonMissionManager, vv16
  LibExtraTip, v5.12.DEV.363(/embedded)
  Masque, v6.0.0
  MasqueCaith, v6.0.0
  MasterPlan, v0.22.1
  MoveAnything, v15.0.7
  OmniCC, v6.0.10
  Postal, v3.5.1
  Prat30, v3.5.10      
  Prat30HighCPUUsageModules, v
  Prat30Libraries, v
  Quartz, v3.2.3
  SavedInstances, v6.0.9
  ShadowedUnitFrames, vv4.0.9
  Stubby, v5.21c.5521 (SanctimoniousSwamprat)
  TidyPlates, v6.15.3
  TidyPlatesGraphite, v
  TidyPlatesGrey, v
  TidyPlatesNeon, v
  TidyPlatesQuatre, v
  TidyPlatesHub, v
  TidyPlatesWidgets, v
  TipHelper, v5.12.DEV.351(/embedded)
  TipTac, v14.10.16
  TipTacItemRef, v14.10.16
  TipTacTalents, v14.10.15
  TomTom, vv60000-1.1.1
  TradeSkillMaster, vv2.10.13
  TradeSkillMasterAccounting, vv2.4.2
  TradeSkillMasterAdditions, vv2.1.3
  TradeSkillMasterAuctionDB, vv2.6.3
  TradeSkillMasterAuctioning, vv2.4.3
  TradeSkillMasterCrafting, vv2.6.16
  TradeSkillMasterDestroying, vv2.1.10
  TradeSkillMasterItemTracker, vv2.1.1
  TradeSkillMasterMailing, vv2.2.10
  TradeSkillMasterShopping, vv2.4.3
  TradeSkillMasterWoWuction, vv2.4
  BlizRuntimeLib_enUS v6.0.3.60000 <none>
  (ck=e21)

**Comment by Adirelle** [comment]
Happens sometimes. Nothing I can do to fix it.
