### ISSUE TITLE
Bug, MM Hunter Procs

### ISSUE THREAD

**Issue by Cursedcruiser** [Adirelle/AdiButtonAuras#149]
The following error occurs occasionally when Kill Shot procs. MM hunter using Bartender 4 and OmniCC addons.

1x [ADDON_ACTION_BLOCKED] AddOn 'AdiButtonAuras' tried to call the protected function 'OverrideActionBarButton3:Show()'.
!BugGrabber\BugGrabber.lua:589: in function <!BugGrabber\BugGrabber.lua:589>
[C]: in function `Show'
FrameXML\ActionButton.lua:301: in function <FrameXML\ActionButton.lua:275>
[C]: in function `ActionButton_Update'
FrameXML\ActionButton.lua:577: in function `ActionButton_OnEvent'
FrameXML\ActionButton.lua:137: in function <FrameXML\ActionButton.lua:134>

Locals:

**Comment by arcadepro** [comment]
I don't think it's an AdiButtonAuras bug. I doubt ABA tries to call the Blizzard Vehicle Bar to update Killshot. I don't even think ABA has any rules for Killshot so the flash is by Blizz anyway.

I've only ever seen this issue myself after performing a reloadui mid raid or after using the config tool of dominos(tuller).

I think Adi played a hunter anyway at one time so he probably would have found this himself if Killshot was broken somehow.

**Comment by Adirelle** [comment]
According to http://www.wowace.com/addons/libbuttonglow-1-0/, using Blizzard flash animations or templates from an addon can taint the action buttons, which would result in these errors. I'm adding LibButtonGlow-1.0, which also supports Masque as an added benefit, to ABA to hopefully fix this.

**Comment by arcadepro** [comment]
Interesting.
