### ISSUE TITLE
Rude Interruption User Rule/LPS Issue.

### ISSUE THREAD

**Issue by arcadepro** [Adirelle/AdiButtonAuras#150]
```
return Configure {
            "Rude",
            L["Rude."],
            "6552",
            "player",
            "UNIT_AURA",
            function(_, model)
                if  GetPlayerBuff("player", 86663) then
                    model.highlight = "good"
                end
            end,
        }
```

Expected result: Draw a green border on the Warrior Pummel [interrupt] button if the player has the buff Rude Interruption(86663).

What happens: The player gets the buff and the border is shown. The angry mob starts to cast a second spell. The green border is removed and a small number appears on the button showing the cast time of the spell. Once the cast/timer is over the green border re-appears. Essentially turning on and off every time the mob casts a new spell.

If pummel is off cooldown and the player still has the buff, the standard 'flash to interrupt' works fine while still showing the mobs cast timer on the button.

Why not simply add this to Libplayerspells since it's a Glyph?

Well there is a similar issue if added to player spells
```
[ 86663] =               6552, -- Glyph of Rude Interruption
```
Timers and borders display as expected apart from in the following case.
If the player has the buff (green border on pummel) and pummel is off cooldown and the mob casts; the standard 'flash to interrupt' does not appear.

**Comment by Adirelle** [comment]
Right now, flash is controlled by the "highlight" attribute, and so it is exclusive to good/bad highlights. Depending on the rule execution order (which we is quite random), rules that sets the flash highlight can be overridden by following rules that set good/bad highlight.

I'll see if I can create an alternate "flash" attribute without breaking existing rules.

**Comment by arcadepro** [comment]
This rule works now. The LPS version also works correctly.
