### ISSUE TITLE
Deterrence

### ISSUE THREAD

**Issue by beastaspect** [Adirelle/AdiButtonAuras#152]
Please add the Hunter survival cooldown Deterrence.

**Comment by Adirelle** [comment]
Should already be working. Are you using a talent or glyph that modifies it ? If yes, please check the "debugging tooltip" option and lists the spell identifiers from spellbook, action bar and the buff.

**Comment by beastaspect** [comment]
Deterrence's id when using the talent Crouching Tiger, Hidden Chimaera is 148467.  The untalented spell id is 19263.
