### ISSUE TITLE
(DK) Connect remorseless-winter

### ISSUE THREAD

**Issue by Tonyleila** [Adirelle/AdiButtonAuras#158]
Key spell in Bars: 108200
Buff on self: 108200 http://www.wowhead.com/spell=108200/remorseless-winter
Slowed stacks (max 5) on target: 115000 http://www.wowhead.com/spell=115000/remorseless-winter
Debuff on target if stunned: 115001 http://www.wowhead.com/spell=115001/remorseless-winter

**Comment by Adirelle** [comment]
Why have you closed this issue ?

**Comment by Tonyleila** [comment]
Because I tryed to make it easy for you instead of one ticket for every spell I fixed it and made one ticket for each class :)
