### ISSUE TITLE
(Monk) Connect Spells: Provoke / Life Cocoon / Transcendence/ Statue

### ISSUE THREAD

**Issue by Tonyleila** [Adirelle/AdiButtonAuras#159]
1. Provoke
in Bars: 115546
Taunted debuff on target: 116189 http://www.wowhead.com/spell=116189/provoke

2. Life Cocoon
Spell in Bars: 116849
Buff on me/target: 116849

3. Transcendence
Spell in Bars: 101643
15 min Buff on me: 101643

4. Summon Jade Serpent Statue
It dosen't always work  hmm 
http://www.wowhead.com/spell=115313/summon-jade-serpent-statue

**Comment by Adirelle** [comment]
1. Should already be good, thanks to DRData-1.0.
2. Added.
3. Fixed.
4. Don't know why it does this. It doesn't have a buff but it is handled like a totem. Gonna make some tests.

**Comment by Tonyleila** [comment]
1. Provoke is still not working even with DRData-1.0
3. Transcendence, sadly not fixed

**Comment by Rainrider** [comment]
Transcendence is working. Maybe check the setting of "maximum duration to show" in the options.
Provoke is not working, I'll take a look.

**Comment by Rainrider** [comment]
1. Working since 1eff0b2fbecedb91df238e5f80dc3926f1cd61d1
2. Is not working for you because you disabled the borders and the buff duration is above the buff duration to be shown threshold. This is the intended behavior.
