### ISSUE TITLE
Removing flash from default rules

### ISSUE THREAD

**Issue by Adirelle** [Adirelle/AdiButtonAuras#164]
I'm thinking about removing flash from rules, e.g. converting existing "flash" into "hint". The idea was that ABA with default settings wouldn't show any flashing animation. However, there are two settings the user could use to get the flashing animation:

* there is a global setting to show "hint" as flash,
* there is a per-spell setting to promote to flash.

I would change the latter to a multiple choice labelled "flash on" with the following options: "hint", "good or bad border", "missing", which should cover most use cases (including the "invert" option).

Any thought ?

**Comment by Rainrider** [comment]
I think flash is cool for interrupts, dispels and abilities that are available only for a short period of time (the last are mostly covered by the default ui though).

I would find an option to globally change the hint and the flash animations nice.

**Comment by Adirelle** [comment]
There is already an option to change the hunt animation globally, though it is limited to "none", "rotary star" and "flashing animation".
