### ISSUE TITLE
[Monk] ShowStacks rule and Elusive Brew

### ISSUE THREAD

**Issue by Rainrider** [Adirelle/AdiButtonAuras#167]
Currently there are 2 handlers for the stack count for Elusive Brew - the one added by the ABA rule for it and I honestly don't know where the other one comes from as ABA fails to name the source:
![elusive brew rules](https://cloud.githubusercontent.com/assets/363876/5948877/ddbc2286-a748-11e4-8e7b-aef842882a65.jpg) - The rule with the unknown source is disabled in the screenshot.

Also the default ui displays the stack count on Elusive Brew, so the rules result in this:
![elusive brew stacks](https://cloud.githubusercontent.com/assets/363876/5948785/fbeb35cc-a747-11e4-812e-58206d667972.jpg) - two different stack counters displaying the same.

**Comment by Adirelle** [comment]
That's probably linked to this commit: https://github.com/Adirelle/AdiButtonAuras/commit/2ddb0f74c8bf0a5236c572e1d420a6bb03861ccf.

**Comment by Rainrider** [comment]
Oh, ok it adds two different rules - one for the stack count and one for the hint. I am sorry, I missed that one.

**Comment by Rainrider** [comment]
Hm, on a second thought, the counter should actually not be shown if the stock counter is visible, should it? https://github.com/Adirelle/AdiButtonAuras/blob/master/core/Display.lua#L144
