### ISSUE TITLE
Suggest using abilities when resources are capped

### ISSUE THREAD

**Issue by Rainrider** [Adirelle/AdiButtonAuras#170]
The whole highlight thing at max resources is somewhat inconsistent across some of the classes.

* For walocks: why highlighting ~~Soulburn~~ Shadowburn, when the target is above 20% (yes we can have a separate rule for this), or why highlighting Brim and Firestone on a single target fight (we can't even detect this)?
* For monks: why highlighting Breath of Fire at max chi, when its debuff is on the target?
* For rogues: Slice and Dice, Crimson Tempest, Kidney Shot are all candidates for custom rules.

So it ends up like the highlight is just there to represent a possible choice (and pushing us to create a lot of custom rules), but the resource count displayed on those buttons is actually exactly the same thing. The only other benefit of the highlight would be to show the player that they capped their resources, which is in my opinion unneeded. I mean everyone knows we can have up to 5 combo points, right? Or at least a less visually intrusive way of showing this would be to just change the color of the counter the same way this is possible for timers below a configurable amount.

What do you think about this?

**Comment by Adirelle** [comment]
I think I'm influenced by different people that have good and valid arguments but from different points of view. This impacted the way I wrote some rules at different points in the past.

**Comment by Rainrider** [comment]
I mean primarily the new behavior of ShowPower.

**Comment by Adirelle** [comment]
The point was to create two default rules that you can disable separately, according to your own tastes.
