### ISSUE TITLE
Not Scaling to Larger Button Sizes

### ISSUE THREAD

**Issue by ArtnerC** [Adirelle/AdiButtonAuras#171]
Just want to say I love this addon and have used it for forever as InlineAuras, it is immensely underrated and thank you for keeping it up.

So I'm trying to use it along with larger buttons, moved towards the middle of the screen, as a type of replacement for what many use WeakAuras for. The problem I'm having is the overlays don't seem to scale with button size. Leaving me with some odd looking buttons... I'm using ElvUI action bars, if it matters. Let me know if you need any more info.

![wowscrnshot_012615_205515](https://cloud.githubusercontent.com/assets/1809503/6011002/4292c394-aaec-11e4-9970-2ffcb15bf9d3.jpg)

**Comment by Rainrider** [comment]
https://github.com/Adirelle/AdiButtonAuras#are-you-going-to-support-elvui-

**Comment by Rainrider** [comment]
I'm closing this for lack of feedback and on the assumption the issue is caused by the skin of ElvUI, which Adirelle stated will not be supported. If you have something to add, please feel free to re-open.

**Comment by xergio** [comment]
For anyone interested, I "fixed" this editing this line: https://github.com/AdiAddons/AdiButtonAuras/blob/master/core/Overlays.lua#L202 with:

```self:SetSize(50, 50)```

(50 or the size of your buttons)

I don't know why `button:GetSize()` gets the wrong button size.

It's a bad solution, but for now this works for me.

**Comment by Rainrider** [comment]
Probably the reason is that the button skin of ElvUI is bigger than the buttons themselves. Your "fix" would be overwritten the next time you update, so you'll have to re-apply it.

I might take a look at it and see if I could easily add support for ElvUI. Don't hold your breath though :)

**Comment by xergio** [comment]
> Your "fix" would be overwritten the next time you update, so you'll have to re-apply it.

Yes, I know, in some way my comment was to remember to myself what to change in the future :P

Thank you for take a look into it! much appreciated!
