### ISSUE TITLE
Is Purge (Shaman) supposed to Flash when you can Purge?

### ISSUE THREAD

**Issue by arcadepro** [Adirelle/AdiButtonAuras#172]
A shaman in raid tonight told me Purge was not working during Thogar/Cauterizing Bolt. Just want to confirm that Purge has no problems akin to the recent Tranqshot/Enrage issues.

I have tested some generic mobs on my Shaman. Purgable mobs show a green border on Purge by default. I suspect it works fine and it was a case of user error.

**Comment by Rainrider** [comment]
As far as I know it should be functional (showing the green border and the duration of the buff to be dispelled). Cauterizing Bolt is a magic buff on an enemy, so the only reason for it not to work would be if the spell id of Purge changes for some reason (we only check if 370 is a known spell by the player). I think I tested with Glyph of cleansing Waters and Glyph of Purge, but maybe I missed something, so it would be kind from you if you could verify that the only possible spell id for purge is 370.

**Comment by Rainrider** [comment]
Please re-open if this needs further attention.
