### ISSUE TITLE
Masque overlay interaction

### ISSUE THREAD

**Issue by chiyeuk** [Adirelle/AdiButtonAuras#174]
A different overlay interaction with Masque was implemented with the newer versions. I couldn't figure out how to change my AdiButtonAuras to look the same again. I've since reverted back to the previous versions without this new interaction. Could you please advise if there is still a way for it to appear as shown below in the newer versions? I've tried turning the option on and off but it did not seem to work? Last I tried, there was also no preview when turning the option on and off until I reload UI.

![image](https://cloud.githubusercontent.com/assets/11138998/6315802/18e613a8-b9c3-11e4-8f95-42476cf33f57.png)

**Comment by Adirelle** [comment]
You can change AdiButtonAuras has its own configuration section in Masque (that you can configure with /masque), so you can eventually use the default skin.

**Comment by Rainrider** [comment]
Is that issue solved?

**Comment by Rainrider** [comment]
Please re-open if this needs further attention.

**Comment by chiyeuk** [comment]
Hi, sorry for slow response (been travelling).

I played around with both the /masque > AdiButtonAuras option as well as AdiButtonAuras > Theme > Use Masque option and have not been able to produce the appearance I had before.

The closest I can get is the attached.

![ss 2015-03-09 at 11 59 41](https://cloud.githubusercontent.com/assets/11138998/6570502/04d0eb4c-c6b9-11e4-997d-abb464fcaac0.jpg)

**Comment by Rainrider** [comment]
Which action bar addon and which masque skin are you using?

**Comment by Rainrider** [comment]
From your screenshot it seems you're trying to use the "bottom to top gradient" highlight texture in ABA's theme options on top of a masque skin.

I was able to recreate your result using Dominos with the Masque: Caith skin, then I removed the check mark from "Use Masque" under ABA's theme options and chose "bottom to top gradient". The highlight texture appeared over-dimensional but a simple reload of the interface fixed this.

![wowscrnshot_031015_170452](https://cloud.githubusercontent.com/assets/363876/6579189/e688432a-c748-11e4-8d4b-dadb002e1159.jpg)

Could you confirm if this fixes it for you?

**Comment by chiyeuk** [comment]
I use Bartender and the Apathy skin for Masque. I got it to work again, following your instructions! Thanks so much.

![ss 2015-03-10 at 09 34 28](https://cloud.githubusercontent.com/assets/11138998/6590442/42779932-c76d-11e4-8827-46c7858892be.jpg)

**Comment by Rainrider** [comment]
It does not look very fixed to me, the highlight texture is still bigger that the button beneath it.

**Comment by chiyeuk** [comment]
I think that's because of how the Apathy Masque skin is (it has a bigger "hitbox" than it looks), but this is exactly how I wanted it to look. Before your instructions fixed it, it was abnormally bigger and overlapped the other buttons. If I switch to the Caith skin, it changes the buttons to the same size of the ABA highlight and would look the same as in your screenshot.
