### ISSUE TITLE
Shaman error on login 6.1

### ISSUE THREAD

**Issue by 2ndHouse** [Adirelle/AdiButtonAuras#176]
Seeing this error on login everytime since 6.1...

2x LibPlayerSpells-1.0-5: 7 errors in SHAMAN database:
Data are probably outdated: data version=60000, client version=60100
Spell #159105: unknown spell
Spell #165344: unknown provider spell
Spell #159101: unknown spell
Spell #165339: unknown provider spell
Spell #159103: unknown spell
Spell #165341: unknown provider spell
...ButtonAuras\libs\LibPlayerSpells-1.0-5\data\Shaman.lua:36: in main chunk

**Comment by Rainrider** [comment]
It appears they changed Echo of the Elements and Ascendance and didn't mention this in the patch notes. It seems safe to remove the entries for the former, as it now adds charges to the spells it modifies. I'll have to dig into wowhead for Ascension though, as my shaman is only level 60 and 6.1 hasn't even been released in Europe yet.
