### ISSUE TITLE
Priest bug

### ISSUE THREAD

**Issue by GoofyShot** [Adirelle/AdiButtonAuras#177]
I am getting spammed with all sorts of errors such as this
![image](https://cloud.githubusercontent.com/assets/8959186/6428807/65e0ecbc-bf74-11e4-8294-b418d53badc1.png)
Also, is there anyway to disable that error report? I'd rather if it wasn't shown  in general tab... I know it's fun this addon but cannot figure out how to disable LUA errors from showing there

**Comment by Rainrider** [comment]
Hi and sorry for the inconvenience. The simplest way to prevent the error from being shown in chat is to install an addon like [BugSack](http://www.wowace.com/addons/bugsack/), which will capture bugs in a sack for you (and play an annoying sound when it does so, but I believe you can turn that off).

Thank you for submitting the bug, I will take a look and keep you updated here.

**Comment by Rainrider** [comment]
Sorry for taking that long to fix this, it just intrigued me to find out when this had broken and I had little spare time the last days.

I also removed the part that apparently warned the player when Evangelism would expire in less than 5 seconds. I don't think this was ever reliable or even functional.
