### ISSUE TITLE
Warlock soul stone showing on cd when its available

### ISSUE THREAD

**Issue by Golheart** [Adirelle/AdiButtonAuras#183]
I haven't done any extensive testing on this but it appears my SS is often showing it is on CD when in fact it is available for use for battle rez.

**Comment by Rainrider** [comment]
AdiButtonAuras does not show CDs but aura durations.

What you've encountered is a (probably) Blizzard bug where the CD text on action buttons is being reset if you get a loading screen while a cooldown is running. The CD text disappears though, when the CD ends. I can reproduce this without AdiButtonAura and/or my actionbar addon loaded.

**Comment by Golheart** [comment]
I've got a ton of addons installed so I suppose it could be something else.  What is happening is that there is a timer on soul stone and it is red but it can still be clicked and used.  This is while raiding (and there are dead folks) and definitely not during or after a loading screen.

I thought perhaps the logic for number of battle rez may be off.

**Comment by Rainrider** [comment]
There is only one rule for Soulstone in ABA. Open ABA options, click on "Spells & Items" and hover your mouse over Soulstone to see how many rules you have.

We don't have a rule for the number of available battle resurrections yet, this is a good idea though.

**Comment by Golheart** [comment]
Ah looks like tullarange was coloring red for distance and omnicc is what is adding the cooldown counts.

thanks!
