### ISSUE TITLE
update for 6.2.0

### ISSUE THREAD

**Issue by dary1125** [Adirelle/AdiButtonAuras#186]
World of Warcraft has been updated to 6.2.0, the plugin has been wrong, hope the author can update for 6.2.0

**Comment by Rainrider** [comment]
I haven't played for a while? What is broken? Do you have any errors related to the addon? Have you enabled "Load out of date addons"?

I'll take a look tomorrow and will update the tocs, maybe that is your issue.

**Comment by Einhorn1967** [comment]
The error is apparently related to the libplayerspells.

Message: LibPlayerSpells-1.0: 2 errors in HUNTER database:
Data are probably outdated: data version=60100, client version=60200
Spell #172106: unknown spell
Debug:
   ...ButtonAuras\libs\LibPlayerSpells-1.0\data\Hunter.lua:23: in main chunk
