### ISSUE TITLE
error since 6.2 release

### ISSUE THREAD

**Issue by Ranthippo** [Adirelle/AdiButtonAuras#187]
1x LibPlayerSpells-1.0-7: 2 errors in MAGE database:
Data are probably outdated: data version=60100, client version=60200
Spell #159916: unknown spell
...diButtonAuras\libs\LibPlayerSpells-1.0-7\data\Mage.lua:23: in main chunk

Locals:
nil

**Comment by Rainrider** [comment]
Fixed in Adirelle/LibPlayerSpells-1.0@54446c451cd65fbe9c9c0e5d33be96ebf2328a9e
