### ISSUE TITLE
Build errors in Pull Request #190

### ISSUE THREAD

**Issue by myth384** [Adirelle/AdiButtonAuras#191]
I'm getting some build errors when submitting pull request #190. It looks like the errors aren't related to my changes though:

...
\>>> testItems:testGetItemSpell1 failed
...
\>>> testItems:testLibItemBuffs1 failed
...

**Comment by Rainrider** [comment]
Yes, those two are known and not related to your PR. I have to update the tests to account for changes I made some time ago to address an issue related to consumables tracking buffs on other players too. I'm closing this, since you fixed the globals and the white space you introduced.
