### ISSUE TITLE
Unable to enable addon spells & items

### ISSUE THREAD

**Issue by N19h7m4r3** [Adirelle/AdiButtonAuras#192]
I recently had a tiny update for WoW through the launcher and since then the addon no longer works.
It is enabled, but for some reason I can no longer enable auras for spells, the tick box cannot be clicked and is always grayed out.
![adibuttons](https://cloud.githubusercontent.com/assets/4963148/9412296/ce843bca-4822-11e5-87d9-507da7892d55.png)

I was running 1.9.4, but the issue persists on 1.9.5 and the 1.9.6 beta; along with disabling my other addons to see if that helps.

Any suggestions would  be greatly appreciated.

**Comment by Rainrider** [comment]
When you click on spells & items the buttons on your action bars that have a rule associated with them should turn green. Clicking on a green button should activate the settings for that button. The add-on is loaded when you can access the settings as in your screenshot.

**Comment by N19h7m4r3** [comment]
Sadly none of that is possible. Clicking on them only activates them. Even in the config mode. There are no longer green buttons, and none of the auras work. It doesn't even darken buttons, or make them red. Simply nothing happens sadly.

**Comment by Rainrider** [comment]
Any errors? Also, ist that elvui by any chance? ABA does not support elvui action bars as far as I know.

**Comment by N19h7m4r3** [comment]
No errors, and until today I've never had issues running ABA with elvui. 
As mentioned, even if I disabled all my addons, including elvui ABA no longer works in any way or form. I'm rather perplexed as until that tiny WoW update came through the launcher today I've had months of perfect use.

**Comment by Rainrider** [comment]
I'll install the latest wow update later today or tommorow and will try to reproduce.

**Comment by N19h7m4r3** [comment]
Thank you, hopefully it's something minor.

**Comment by mikevaleriano** [comment]
Having the same issue, but I suspect it has to do with the latest ElvUI. Updated it today, and after logging in, had the same problem.

Trying to find an "older versions" link from Tukui but haven't found one so far. Ugh.

**Comment by N19h7m4r3** [comment]
Thank you ever so much Mikevaleriano! I thought it might have been the WoW update, but you were entirely correct. Thank you for the download link.

**Comment by mikevaleriano** [comment]
Coolio. I'll just wait for the next version of ElvUI to try and update, and see if it won't break ABA again. And keep this 8.25 for a while.

**Comment by Rainrider** [comment]
Well, they renamed LibActionButtons because they apparently have a custom version of it. Maybe that is the reason why it stopped working. If this is the only major difference it should be easy to handle that in ABA. I'll take a look when time permits.
