### ISSUE TITLE
To hint or not to hint... that's the question.

### ISSUE THREAD

**Issue by myth384** [Adirelle/AdiButtonAuras#194]
I have some ideas about certain spell conditions which could be very helpful for monks to be indicated by an hint. But I can imagine you don't want AdiButtonAuras become a second Bitten's Spellflash. So what are your guidelines for what should be indicated by an hint and what not?

**Comment by Rainrider** [comment]
In general flash is for a necessity and hint for a possibility. For a rule to be included in ABA it has to appeal to a broader audience. Other than that you should avoid hinting the whole action bar as pulling attention to too much choice defeats the purpose of hints.
