### ISSUE TITLE
ElvUI issue

### ISSUE THREAD

**Issue by CibiX** [Adirelle/AdiButtonAuras#195]
It seems the ElvUI issue is not solved. AdiButtonAuras doesn't work with ElvUI version 8.26. Unfortunately I don't know why. There is no error showing

**Comment by alumit** [comment]
As a temp fix you can change "LibActionButton-1.0" to "LibActionButton-1.0-ElvUI" in the Core.lua
Yoe need to do this on a few lines. Thet "fixed" it for me for now.

**Comment by Rainrider** [comment]
This is actually already done and an updated version is on wowace.

**Comment by CibiX** [comment]
I see version 1.9.5 on wowace and this version does not work with ElvUI 8.26. So far I have downgraded my ElvUI to 8.25 where all works ok.

**Comment by Rainrider** [comment]
![aba_wowace](https://cloud.githubusercontent.com/assets/363876/9501777/87d30fc6-4c2d-11e5-90de-a35720b38f61.png)

Look at me! Now back at your browser! Now back at me!

**Comment by CibiX** [comment]
I didn't check the betas. Thank you :)
