### ISSUE TITLE
Unable to get AdiDebug working

### ISSUE THREAD

**Issue by myth384** [Adirelle/AdiButtonAuras#204]
I'm unable to get *AdiDebug* working with *AdiButtonAuras*. I have extracted the ZIP-file from Github to my addon folder and renamed the folder to *AdiDebug*. I have added the libraries *AceDB-3.0*, *CallbackHandler-1.0* and *LibStub* to the *lib* folder.
*AdiDebug* is present in the *AddOn List* ingame, but it is *Only loadable on demand*
Both slash commands aren't working.
Can you help me out please? I'm debugging now using `print()`, but I really would like to use the facilities Adirelle made. :-)

**Comment by Rainrider** [comment]
Move the AdiDebug_GUI folder to your addons folder. I think you also need tekDebug. This is actually not related to AdiButtonAuras.

**Comment by Adirelle** [comment]
You don't need tekDebug. AdiDebug actually emulates it, so you will also get debug from tekkub's addons.

**Comment by myth384** [comment]
Thanks! That did the job.
