### ISSUE TITLE
Rogue Shadow Blades buff overrides Revealing Strike Aura

### ISSUE THREAD

**Issue by dafzor** [Adirelle/AdiButtonAuras#31]
the following code in LibPlayerSpells-1.0\data\Rogue.lua:

	[121471] = {  Shadow Blades =>
		 1752,  Sinister Strike
		84617,  Revealing Strike
		51723,  Fan of Knives
		 1833,  Cheap Shot
		 8676,  Ambush
		  703,  Garrote
	},

overrides the aura already displayed on Revealing Strike, since the duration is already shown on the cd button duplicating it by hiding other debuff information is unneeded and unwanted. Commenting it out resolves the issue.

**Comment by Rainrider** [comment]
Shadow Blades has been removed in WoD.
